---
- name: Get-URL download the protected file
  hosts: localhost
  tasks:
    - name: Download the file
      ansible.builtin.get_url:
        url: https://filesamples.com/samples/document/txt/sample2.txt
        dest: /tmp/sample2.txt

    - name: Display the file contents
      ansible.builtin.shell: >
         cat /tmp/sample2.txt
      register: shellout

    - name: Show file stdout output
      ansible.builtin.debug: 
        var: shellout.stdout_lines