---
- name: check date play
  hosts: ubuntu
  gather_facts: False
  tasks:
    - name: check date
      command: date
      register: sys_date
    - name: show date
      debug:
        msg: "System date : {{sys_date.stdout_lines}}"

- name: check uptime play
  hosts: ubuntu
  gather_facts: False
  tasks:
    - name: check uptime
      command: uptime
      register: sys_uptime
    - name: show uptime
      debug:
        msg: "System uptime : {{sys_uptime.stdout_lines}}"