---
- name: Check date play
  hosts: ubuntu
  gather_facts: false
  tasks:
    - name: Check date
      ansible.builtin.command: date
      register: sys_date
      changed_when: false
    - name: Show date
      ansible.builtin.debug:
        msg: "System date: {{ sys_date.stdout_lines }}"

- name: Check uptime play
  hosts: ubuntu
  gather_facts: false
  tasks:
    - name: Check uptime
      ansible.builtin.command: uptime
      register: sys_uptime
      changed_when: false
    - name: Show uptime
      ansible.builtin.debug:
        msg: "System uptime: {{ sys_uptime.stdout_lines }}"
